### ISSUE TITLE
Error in `purrr::map()

### ISSUE THREAD

**Issue by ved-ux** [Chrisjb/basemapR#6]
> ggplot() +
+   base_map(bbox = my_bbox, basemap = 'hydda', increase_zoom = 2) +
+   geom_sf(data = camden, fill = NA) +
+   geom_sf(data = wandsworth, fill = NA) +
+   ggthemes::theme_map()
attribution: Tiles courtesy of http://openstreetmap.se/ OpenStreetMap Sweden; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `curl::curl_download()`:
! Timeout was reached: [] Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
Run `rlang::last_trace()` to see where the error occurred.

**Comment by mwip** [comment]
This is likely linked to https://github.com/karlwettin/carto-style-hydda/issues/3

**Comment by Chrisjb** [comment]
Closing as seems to be an issue specific to the openstreetmap.se server with no clear solution. Open to removing the style from the available basemap options to avoid confusion
